---
- name: Drift Detection Rulebook
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 100
        delay: 60

  rules:
    - name: Trigger drift detection
      condition: event.i >= 0
      action:
        run_job_template:
          name: "2 - Detect Drift"
          organization: Default
